## Class Task 2

### Question 1



The number of rows and columns 
A = [2x3]
B = [3x2]
The matrices can be multiplied because matrix A has 3 columns and matrix B has 3 Rows and equally matrix B has 2 columns and matix A has 2 rows. Therefore the multiplication can be done both ways


### Question 2

The matrices can be multiplied because matrix A has 3 columns and matrix B has 3 Rows and equally matrix B has 2 columns and matix A has 2 rows. Therefore the multiplication can be done both ways

### Question 3

In [7]:
import numpy as np
# Defining matrix A
matA = np.array([[2,-1,3], [0,4,1]])
matA


array([[ 2, -1,  3],
       [ 0,  4,  1]])

In [ ]:
# Defining matrix B
matB = np.array([[1,2], [-2,0], [5,-3]])
matB

array([[ 1,  2],
       [-2,  0],
       [ 5,  3]])

#### Multiplying AxB

In [9]:
# Performing matrix multiplication
multiply = matA @ matB
multiply

array([[19, 13],
       [-3,  3]])

### Multiplying BxA

In [10]:
multiply = matB @ matA
multiply

array([[ 2,  7,  5],
       [-4,  2, -6],
       [10,  7, 18]])