### Class Task 4

In [3]:
import numpy as np



# Creating row vectors for each student information
student1 = np.array([80, 70, 90])
student2 = np.array([60, 85, 75])
student3 = np.array([95, 88, 92])
student4 = np.array([70, 60, 65])



print(f"Student 1: \n{student1}")
print(f"Student 1: \n{student2}")
print(f"Student 1: \n{student3}")
print(f"Student 1: \n{student4}")



Student 1: 
[80 70 90]
Student 1: 
[60 85 75]
Student 1: 
[95 88 92]
Student 1: 
[70 60 65]


Representing Data as Matrix

$$ 
Data =\begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65
\end{bmatrix}

$$

In [4]:
# Representing the data as a matrix
data = np.array([[80, 70, 90],
                [60, 85, 75],
                [95, 88, 92],
                [70, 60, 65]])

print(f"The Matrix for Data sheet: \n{data}")

The Matrix for Data sheet: 
[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


Total Score for Each Students = [240 220 275 295]
Total Score for student 1 = 240
Total Score for student 2 = 220
Total Score for student 3 = 275
Total Score for student 4 = 195

In [ ]:

total_scores = np.sum(data, axis=1)
print(f"Total scores for each student {total_scores}")

i=1
for  student_scores in total_scores:
    print(f"Total Scores for student {i} = {student_scores}")
    i+=1

Total scores for each student [240 220 275 195]
Total Scores for student 1 = 240
Total Scores for student 2 = 220
Total Scores for student 3 = 275
Total Scores for student 4 = 195


### 3.3 Applying Weights

To apply Weight to Subjects

$$ 
Data = 2 * \begin{bmatrix}
80 \\
60  \\
95  \\
70 
\end{bmatrix}

$$

$$


$$ 
Data =\begin{bmatrix}
160 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65
\end{bmatrix}

$$

In [6]:
# Applying Weight to Subject Math
data[:, 0] = 2 * (data[:, 0])

print(f" Subjects Weight \n {data}")

 Subjects Weight 
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


### 3.4 Average Score per subject

In [10]:
average_score = np.mean(data, axis=0)
print(f"Average score \n {average_score}")
i = ['Math', 'English', 'Science']

for subjects, all_average in zip(i, average_score):
    print(f"Average Score for {subjects} = {all_average}")

Average score 
 [152.5   75.75  80.5 ]
Average Score for Math = 152.5
Average Score for English = 75.75
Average Score for Science = 80.5


### 3.5 Final Grades Multiplication

In [8]:
grades_scale = np.array([0.5, 0.3, 0.2])

final_math = np.dot(grades_scale[0], data[:, 0])
print(f" Final Grade for Math \n {final_math.reshape(4,1)}")


final_eng = np.dot(grades_scale[0], data[:, 1])
print(f"Final Grade for English \n {final_eng.reshape(4,1)}")

final_sci = np.dot(grades_scale[0], data[:, 2])
print(f" Final Grades for Science \n {final_sci.reshape(4,1)}")


 Final Grade for Math 
 [[80.]
 [60.]
 [95.]
 [70.]]
Final Grade for English 
 [[35. ]
 [42.5]
 [44. ]
 [30. ]]
 Final Grades for Science 
 [[45. ]
 [37.5]
 [46. ]
 [32.5]]


### 3.6 Comparing Performance

In [9]:
performance = np.diff()

TypeError: diff() missing 1 required positional argument: 'a'

## ADD On Exercise

In [ ]:
scores = np.array([[80,70,90,50],[60,85,75,60],[95,88,92,70],[70,60,65,80],[70,55,75,60]])
student1_scores = np.array([80,70,90,50])
student2_scores = np.array([60,85,75,60])
student3_scores = np.array([95,88,92,70])
student4_scores = np.array([70,60,65,80])
student5_scores = np.array([70,55,75,60])
print(scores)

[[80 70 90 50]
 [60 85 75 60]
 [95 88 92 70]
 [70 60 65 80]
 [70 55 75 60]]


#### Total Scores

In [ ]:
total_scores = np.sum(scores, axis=1)
print(f"Total scores for each student {total_scores}")

i=1
for  stud_scores in total_scores:
    print(f"Total Scores for student {i} = {stud_scores}")
    i+=1

Total scores for each student [290 280 345 275 260]
Total Scores for student 1 = 290
Total Scores for student 2 = 280
Total Scores for student 3 = 345
Total Scores for student 4 = 275
Total Scores for student 5 = 260


#### Average Score

In [ ]:
avg_score = np.average(scores, axis= 0)
sub = ['Math', 'English', 'Science']

for subs, all_avg in zip(avg_score, sub):
    print(f" Average score for {all_avg} = {subs}")

 Average score for Math = 75.0
 Average score for English = 71.6
 Average score for Science = 79.4


### 2.

In [ ]:
# Applying Weight to Subject Math
scores[:, 2] = 3 * (scores[:, 2])

print(f" Subjects Weight \n {scores}")

 Subjects Weight 
 [[ 80  70 270  50]
 [ 60  85 225  60]
 [ 95  88 276  70]
 [ 70  60 195  80]
 [ 70  55 225  60]]


### 3.

In [ ]:
new_grading_weights = [0.4, 0.2, 0.3, 0.1]

grade_sub1 = np.dot(new_grading_weights[0], scores[:,0])
print(f" Final Grade for Subject 1 \n {grade_sub1.reshape(5,1)}")


 Final Grade for Subject 1 
 [[32.]
 [24.]
 [38.]
 [28.]
 [28.]]
